# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-05 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
