# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-05 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Book', '0002_auto_20200405_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='作者名字')),
            ],
            options={
                'verbose_name': '作者表',
                'verbose_name_plural': '作者表',
                'db_table': '作者表',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='图书的名称')),
                ('course_img', models.CharField(help_text='图片网址链接', max_length=255, verbose_name='图书的图片')),
                ('brief', models.CharField(max_length=1024, verbose_name='图书简介')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='上架日期')),
                ('isbn', models.CharField(max_length=32, verbose_name='ISBN')),
                ('issn', models.CharField(blank=True, max_length=32, null=True, verbose_name='ISSN')),
                ('bpan_link', models.CharField(max_length=255, verbose_name='网盘链接')),
                ('bpan_code', models.CharField(max_length=8, verbose_name='提取码')),
                ('foreign_book_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='外文书名')),
                ('language', models.SmallIntegerField(choices=[(0, '中文'), (1, '英语')], default=0, verbose_name='语言')),
                ('order', models.IntegerField(help_text='从上一个图书数字往后排', verbose_name='图书顺序')),
                ('first_category', models.SmallIntegerField(choices=[(0, '小说'), (1, '文学'), (2, '人文社科'), (3, '经济管理'), (4, '科技科普'), (5, '计算机于互联网'), (6, '成功励志'), (7, '生活'), (8, '少儿'), (9, '艺术设计'), (10, '漫画绘本'), (11, '教育考试'), (12, '杂志')], verbose_name='一级分类')),
                ('book_tag', models.SmallIntegerField(choices=[(0, '古典'), (1, '投资'), (2, '短篇'), (3, '文化'), (4, '政治'), (5, '大家小书'), (6, '心理学'), (7, '旅行'), (8, '恋爱'), (9, '书单'), (10, '三毛'), (11, '学习'), (12, '中篇'), (13, '经典'), (14, '长篇'), (15, '诗词'), (16, '创业'), (17, '阅读'), (18, '文艺'), (19, '散文'), (20, '哲学'), (21, '下载'), (22, '外国文学'), (23, '人物'), (24, '日本'), (25, '心灵'), (26, '励志'), (27, '生活'), (28, '合集'), (29, '中国'), (30, '必读'), (31, '随笔'), (32, '社会'), (33, '英国'), (34, '经济'), (35, '思享'), (36, '青春'), (37, '爱情'), (38, '成长'), (39, '文学'), (40, '小说'), (41, '美国'), (42, '历史'), (43, '情感'), (44, '人生')], default=0, verbose_name='标签')),
                ('editer', models.CharField(blank=True, max_length=64, null=True, verbose_name='编者')),
                ('proofreader', models.CharField(blank=True, max_length=64, null=True, verbose_name='译者')),
                ('remarker', models.CharField(blank=True, max_length=64, null=True, verbose_name='校对')),
                ('transfer', models.CharField(blank=True, max_length=64, null=True, verbose_name='译者')),
                ('drawer', models.CharField(blank=True, max_length=64, null=True, verbose_name='绘者')),
                ('publishers', models.CharField(blank=True, max_length=64, null=True, verbose_name='出版社')),
                ('publish_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='出版社号')),
                ('series', models.CharField(blank=True, max_length=64, null=True, verbose_name='丛书名')),
                ('brand', models.CharField(blank=True, max_length=64, null=True, verbose_name='品牌')),
                ('format', models.CharField(blank=True, max_length=64, null=True, verbose_name='格式')),
                ('packages', models.CharField(blank=True, max_length=64, null=True, verbose_name='包装')),
                ('pages', models.CharField(blank=True, max_length=64, null=True, verbose_name='页数')),
                ('batch_no', models.CharField(blank=True, max_length=64, null=True, verbose_name='版次')),
                ('publish_time', models.CharField(blank=True, max_length=64, null=True, verbose_name='出版时间')),
                ('print_no', models.SmallIntegerField(blank=True, null=True, verbose_name='印次')),
                ('print_time', models.CharField(blank=True, max_length=64, null=True, verbose_name='印刷时间')),
                ('size_and_height', models.CharField(blank=True, max_length=64, null=True, verbose_name='尺寸及重量')),
                ('china_catalog', models.CharField(blank=True, max_length=64, null=True, verbose_name='中国法分类号')),
                ('sheet', models.CharField(blank=True, max_length=64, null=True, verbose_name='印张')),
                ('papers', models.CharField(blank=True, max_length=64, null=True, verbose_name='用纸')),
                ('attachment', models.CharField(blank=True, max_length=64, null=True, verbose_name='附件')),
                ('attachment_num', models.SmallIntegerField(blank=True, null=True, verbose_name='附件数量')),
                ('pack_num', models.SmallIntegerField(blank=True, null=True, verbose_name='套装数量')),
                ('letters', models.SmallIntegerField(blank=True, null=True, verbose_name='字数')),
                ('bar_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='条形码')),
                ('keywords', models.CharField(blank=True, max_length=64, null=True, verbose_name='主题词')),
                ('pick_state', models.CharField(blank=True, max_length=64, null=True, verbose_name='捡货标记')),
                ('compile', models.CharField(blank=True, max_length=64, null=True, verbose_name='编纂')),
                ('photography', models.CharField(blank=True, max_length=64, null=True, verbose_name='摄影')),
                ('dictation', models.CharField(blank=True, max_length=64, null=True, verbose_name='口述')),
                ('read', models.CharField(blank=True, max_length=64, null=True, verbose_name='朗读')),
                ('finishing', models.CharField(blank=True, max_length=64, null=True, verbose_name='整理')),
                ('write', models.CharField(blank=True, max_length=64, null=True, verbose_name='书写')),
                ('jdPrice', models.SmallIntegerField(blank=True, null=True, verbose_name='原价')),
                ('martPrice', models.SmallIntegerField(blank=True, null=True, verbose_name='当前价')),
                ('skuId', models.CharField(blank=True, max_length=64, null=True, verbose_name='商品编号')),
                ('authors', models.ManyToManyField(to='Book.Author', verbose_name='作者')),
                ('related_books', models.ManyToManyField(blank=True, null=True, related_name='related_by', to='Book.Book')),
            ],
            options={
                'verbose_name': '图书表',
                'verbose_name_plural': '图书表',
                'db_table': '图书表',
            },
        ),
    ]
