# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-07 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0003_author_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AlterField(
            model_name='book',
            name='book_tag',
            field=models.SmallIntegerField(choices=[(1, '投资'), (2, '短篇'), (3, '文化'), (4, '政治'), (5, '大家小书'), (6, '心理学'), (7, '旅行'), (8, '恋爱'), (9, '书单'), (10, '三毛'), (11, '学习'), (12, '中篇'), (13, '经典'), (14, '长篇'), (15, '诗词'), (16, '创业'), (17, '阅读'), (18, '文艺'), (19, '散文'), (20, '哲学'), (21, '下载'), (22, '外国文学'), (23, '人物'), (24, '日本'), (25, '心灵'), (26, '励志'), (27, '生活'), (28, '合集'), (29, '中国'), (30, '必读'), (31, '随笔'), (32, '社会'), (33, '英国'), (34, '经济'), (35, '思享'), (36, '青春'), (37, '爱情'), (38, '成长'), (39, '文学'), (40, '小说'), (41, '美国'), (42, '历史'), (43, '情感'), (44, '人生'), (45, '古典')], default=0, verbose_name='标签'),
        ),
        migrations.AlterField(
            model_name='book',
            name='first_category',
            field=models.SmallIntegerField(choices=[(1, '文学'), (2, '人文社科'), (3, '经济管理'), (4, '科技科普'), (5, '计算机于互联网'), (6, '成功励志'), (7, '生活'), (8, '少儿'), (9, '艺术设计'), (10, '漫画绘本'), (11, '教育考试'), (12, '杂志'), (13, '小说')], verbose_name='一级分类'),
        ),
        migrations.AlterModelTable(
            name='author',
            table=None,
        ),
        migrations.AlterModelTable(
            name='book',
            table=None,
        ),
    ]
