# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-09 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_auto_20200407_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name': '验证码',
                'verbose_name_plural': '验证码',
            },
        ),
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': '作者表', 'verbose_name_plural': '作者表'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': '图书表', 'verbose_name_plural': '图书表'},
        ),
    ]
