# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-10 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_auto_20200410_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='accesscode',
            name='access_code',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_tag',
        ),
        migrations.AddField(
            model_name='book',
            name='book_tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='Book.Book'),
        ),
    ]
