# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-10 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_auto_20200410_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '标签', 'verbose_name_plural': '标签'},
        ),
        migrations.AlterField(
            model_name='book',
            name='book_tag',
            field=models.ManyToManyField(blank=True, null=True, related_name='tag', to='Book.Tag'),
        ),
    ]
