# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-10 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0008_auto_20200410_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='course_img',
            new_name='book_img',
        ),
    ]
