# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-04-11 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0009_auto_20200410_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_img',
            field=models.CharField(default=0, help_text='图片网址链接', max_length=255, verbose_name='图书的图片'),
        ),
    ]
